name: "Scenamatica Scenario Test"
description: "Test your PaperMC Plugin with declared scenario."
author: "TeamKUN., Peyang"
branding:
  icon: book-open
  color: blue
inputs:
  minecraft:
    description: "Target Minecraft version."
    default: "1.16.5"
  server-dir:
    description: "Server directory."
    default: "server"
  plugin:
    description: "The path to your plugin jar file."
    required: true
  scenamatica:
    description: "Target Scenamatica version."
    required: true
  fail-threshold:
    description: "The number of failed tests that will cause the action to fail. Negative values will cause the action to always pass."
    default: "0"
  github-token:
    description: "GitHub token for writing pull request comments."
    default: "${{ github.token }}"
outputs:
  # Runner outputs
  success:
    description: "A boolean value indicating whether the runner successfully processed the tests."
  runner-error-type:
    description: "The error type (like java exception) reported by the runner."
  runner-error-message:
    description: "The error message reported by the runner."

  # Tests outputs (only available when success is true)
  tests:
    description: "The number of tests that were run."
  test-passes:
    description: "The number of tests that passed."
  test-failures:
    description: "The number of tests that failed."
  test-skips:
    description: "The number of tests that were skipped."
  test-cancels:
    description: "The number of tests that were cancelled."

runs:
  using: node16
  main: "src/dist/index.js"
